### ISSUE TITLE
no find "hash/maphash"

### ISSUE THREAD

**Issue by akzj** [dgryski/go-rendezvous#3]
no find "hash/maphash"

**Comment by cqueinnec** [comment]
Looks like the use of `hash/maphash` requires Go 1.14+.

**Comment by dgryski** [comment]
Given that it's only used in `rdv_test.go`, we could easily swap it out for `hash/fnv` to maintain compatibility with older Go versions.

**Comment by eahrend** [comment]
Getting this as well, since I'm trying to implement go-redis v8 in a GCF, the latest version of go they have is 1.13, which doesn't have hash/maphash

**Comment by dgryski** [comment]
Ok, I'll switch to hash/fnv.
